/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package if2212_tb_01_01;

import javax.swing.JFrame;

import if2212_tb_01_01.assets.AssetManager;

import java.awt.image.BufferedImage;

public class Main {
    public Main() {
        /* Create a main window frame for the game */
        JFrame window = new JFrame("Sim-plicity");
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setResizable(false);


        /* Create a game panel */
        GamePanel gamePanel = new GamePanel();
        window.add(gamePanel);

        AssetManager am = new AssetManager(gamePanel);
        BufferedImage logo = am.setup("/logo",16,16);
        window.setIconImage(logo);

        window.pack();
        window.setLocationRelativeTo(null);
        window.setVisible(true);

        gamePanel.setupGame();
        gamePanel.startWorldClock();
        gamePanel.startGameThread();
    }

    public static void main(String[] args) {
        new Main();
    }
}
